### Site Settings ###
title               : Sam Canonaco
description         : >-
                      I turn code into fun,
                      this is my portfolio site,
                      so check out my projects!
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : agentsamx/publicWebsite     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name              : Sam Canonaco
  image             : https://media.licdn.com/dms/image/v2/D5603AQHrM1nTsjK4IA/profile-displayphoto-crop_800_800/B56ZwfusGKI4AM-/0/1770058859390?e=1775692800&v=beta&t=yEQAkFqVVbrgGAv1ROcydLkGw4-Mp1fqVl6VrnLpOus
# behance           : your_username
# dribbble          : your_username
  email             : sam@canona.co
# facebook          : your_username
  github            : agentsamx
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : sam-canonaco
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
